### ISSUE TITLE
npm install is producing a 404

### ISSUE THREAD

**Issue by TylerEich** [babel/babel-connect#7]
`http://registry.npmjs.org/babel-connect/-/babel-connect-6.0.1.tgz` throws a 404

**Comment by sebmck** [comment]
Looks like you're running a really old version of npm. Works fine for me:

``` sh
$ npm install babel-connect
babel-connect@6.0.1 node_modules/babel-connect
├── through@2.3.4
├── lodash@2.4.1
└── mkdirp@0.5.1 (minimist@0.0.8)
```

**Comment by TylerEich** [comment]
Updated from `npm@2.7.5` => `npm@2.9.1`. Still throwing.

```
$ npm install babel-connect
npm ERR! fetch failed https://registry.npmjs.org/babel-connect/-/babel-connect-6.0.1.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
```

**Comment by sebmck** [comment]
Looks like it was downloading it for cache for me. This is without a doubt an npm issue. This URL is provided in the [manifest](https://registry.npmjs.org/babel-connect). I'd recommend taking this up with the npm folks because it looks pretty serious and likely effects other packages.

**Comment by sebmck** [comment]
I've tweeted at them [here](https://twitter.com/sebmck/status/599027234540781568).

**Comment by TylerEich** [comment]
Sounds good, thanks for the quick response!

**Comment by dead-claudia** [comment]
@sebmck

Could you republish this? I'm running into the same problem with identical output, and [republishing this appears to be the fix. (TL;DR: it may have been caused by a broken `crypto.Hash` implementation in Node 0.11.16.)](https://github.com/npm/npm/issues/8822#issuecomment-119431682)

**Comment by sebmck** [comment]
Done

**Comment by dead-claudia** [comment]
@sebmck Damn, that was quick...
